name: Weekly Dependency Check

on:
  schedule:
    - cron: '00 05 * * 2'
  workflow_dispatch:

jobs:
  check-outdated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-outdated
        run: cargo install cargo-outdated

      - name: Run cargo outdated
        run: cargo outdated -p simplicityhl --exit-code 1 --format json > outdated.json

      - name: Print outdated.json
        if: always()
        run: cat outdated.json | jq

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: outdated-results
          path: outdated.json
          retention-days: 8
